export interface Password {
  _id: string;
  title: string;
  username: string;
  password: string;
  category:
    | "AirBnB"
    | "Amazon Prime"
    | "Amazon Shopping"
    | "Amazon"
    | "ArtStation"
    | "ARZone"
    | "Authenticator (Google)"
    | "Authenticator (Microsoft)"
    | "Authy"
    | "Battle"
    | "Booking"
    | "Calendar (Google)"
    | "Chrome (Google)"
    | "CityMapper"
    | "Cuenta DNI"
    | "Currents (Google)"
    | "DeviantArt"
    | "Discord"
    | "Docs (Google)"
    | "Drive (Google)"
    | "Duolingo"
    | "Edge (Microsoft)"
    | "Evernote"
    | "Excel (Microsoft)"
    | "Facebook"
    | "Files (Google)"
    | "Firefox"
    | "Forms (Google)"
    | "Galaxy Store"
    | "Glovo"
    | "Gmail"
    | "Google Launcher"
    | "Google"
    | "Hangouts (Google)"
    | "Idealista"
    | "Instagram"
    | "Itchio"
    | "Keep (Google)"
    | "Ko-Fi"
    | "Link to Windows (Microsoft)"
    | "LinkedIn"
    | "London Guide"
    | "London Offline Map"
    | "London Tube Map"
    | "Maps (Google)"
    | "Mercadolibre"
    | "Mercadopago"
    | "Messenger (Facebook)"
    | "Mi Argentina"
    | "Microsoft Launcher"
    | "Miro"
    | "Moj"
    | "Netflix"
    | "Notion"
    | "Nova Launcher"
    | "Office"
    | "OneDrive (Microsoft)"
    | "OneNote (Microsoft)"
    | "Opera"
    | "Outlook (Microsoft)"
    | "Patreon"
    | "PayPal"
    | "PedidosYa"
    | "Photos (Google)"
    | "Pinterest"
    | "Playstore (Google)"
    | "Podcasts (Google)"
    | "PowerPoint (Microsoft)"
    | "Presentations (Google)"
    | "Publisher (Microsoft)"
    | "Reddit"
    | "Safari"
    | "Samsung Free"
    | "Santander"
    | "Sheets (Google)"
    | "Skype"
    | "Slack"
    | "Snapchat"
    | "SocioPlus"
    | "SoundCloud"
    | "Spotify"
    | "Steam"
    | "Talkback (Google)"
    | "Tarjeta Transporte Madrid"
    | "Telegram"
    | "Text to Speech (Google)"
    | "Tfl Go"
    | "Tfl Oyster"
    | "TickTick"
    | "TikTok"
    | "Tinder"
    | "To do (Microsoft)"
    | "Todoist"
    | "Toggl Blue Icon"
    | "Toggl Hire"
    | "Toggl Plan"
    | "Toggl Track"
    | "Toggl"
    | "Translate (Google)"
    | "Trello"
    | "Tumblr"
    | "TV (Google)"
    | "Twitch"
    | "Twitter"
    | "Uber Eats"
    | "Uber"
    | "Vivaldi"
    | "Whatsapp"
    | "Wikipedia"
    | "WinRAR"
    | "Word (Microsoft)"
    | "Youtube"
    | "Zoom";
}
